### ISSUE TITLE
Disable YouTube support in groups 

### ISSUE THREAD

**Issue by Armin2208** [9dogs/tg-odesli-bot#12]
Your bot works great and helps us sharing music, because nearly everyone of us uses a different music streaming service.

But one thing has annoyed us. The bot also removes YouTube links and turns them to odesli bot music messages. Even though we didn't share a music video, just a normal video.

It would be nice if you would add a option to disable YouTube link support in groups. Thanks!

**Comment by AlexWayfer** [comment]
Or maybe it should get a video category (there is "Music" possible) and convert only music videos.

**Comment by 9dogs** [comment]
Oh man, I've completely overlooked that case! From a quick glance at YouTube API, we can check  category fairly easy, but will it be enough to resolve the annoyance? There are a lot of music videos/concerts which are YouTube-specific, those links should bypass the bot completely.

I guess the choice here is between:
- disable YouTube links handling in group chats completely (in bright future it should be possible to disable it per-chat)
- leave YouTube links handling for "Music" category only with a chance of "false positives" from time to time

**Comment by AlexWayfer** [comment]
@9dogs please, be aware of YouTube API rate limits, especially free ones.

**Comment by fronbasal** [comment]
@9dogs I believe it would be sane to disable YouTube links in groups, as there are many groups sharing such links. I believe it is better to allow YouTube links for the inline Bot API and direct messaging.

**Comment by 9dogs** [comment]
Sorry for the delay. Yes, it is indeed a good temporary solution (well, you know these _temporary solutions_ 😃). Corresponding changes are pushed to master.
@Armin2208, could you check YouTube links now? Should be better.

**Comment by 9dogs** [comment]
I'm closing the issue, feel free to reopen if I've missed something.

**Comment by Armin2208** [comment]
works nice thank you :)
