### ISSUE TITLE
Inline mod no more working

### ISSUE THREAD

**Issue by Satont** [9dogs/tg-odesli-bot#14]
Hi.

I'm trying use inline mod, via `@odesli_bot link` in some private chat, but seems like it's no more working.

**Comment by 9dogs** [comment]
Hey, can you specify the link you have issues with? I don't see any errors in logs.

**Comment by Satont** [comment]
@9dogs i mean inline window even never appears.

I figured out, it's an bug in desktop client of Telegram, will create issue in another place.

Thank you for the reply.
