### ISSUE TITLE
Don't write `1.` for single found entity

### ISSUE THREAD

**Issue by AlexWayfer** [9dogs/tg-odesli-bot#3]
Hello (again)!

I appreciate an ability of bot to recognize multiple links in a message and to respond with a single message.

But I think that `1.` is unnecessary and confusing for single-entity-message, like "what next? where is the second one?".

**Comment by 9dogs** [comment]
Hi!
I see your point and it's actually an artifact of the past. This will be fixed soon.

**Comment by AlexWayfer** [comment]
Thank you!

**Comment by 9dogs** [comment]
You are welcome. I decided to keep an index if some text is present in a message to mark the position of a link. Otherwise it looked unnatural in some cases.
