### ISSUE TITLE
Make able search by Odesli link

### ISSUE THREAD

**Issue by AlexWayfer** [9dogs/tg-odesli-bot#33]
Hello.

I've found a track on Odesli by title.

Unfortunately, bot can't accept links to Odesli itself.

For example: https://song.link/ru/i/1448064354

Although Odesli by itself able to search pages by links to itself (too many "itself", I guess).

**Comment by 9dogs** [comment]
You can now search by title in inline mode. And happy anniversary, issue! 🎉

**Comment by AlexWayfer** [comment]
It's a great feature, but it's different. I'm sorry, but search by Odesli link still doesn't work:

![image](https://user-images.githubusercontent.com/6510020/223096664-fe1a50fb-d231-468e-81bc-b974680ea7e3.png)

**Comment by AlexWayfer** [comment]
> Do you still need it?

Not a lot, but I see that you've done text search via Spotify, and please keep in mind that not every track is in Spotify.

The mentioned search in Odesli works via Apple Music, so there possible cases like this one:

![image](https://user-images.githubusercontent.com/6510020/223099629-14e0fa15-bb0e-44d2-87a8-6b5643599731.png)

https://song.link/i/1640772188

![image](https://user-images.githubusercontent.com/6510020/223099709-ec4f22d4-93eb-4771-a0e8-b7927b18a235.png)

**Comment by 9dogs** [comment]
Yeah, the Apple Developer program costs $90 per month. Spotify is free.

**Comment by AlexWayfer** [comment]
I'm not against Spotify, I'm just saying that the text search feature can't find everything on Odesli, and the bot still doesn't support Odesli's links. That's it.

If you don't want to implement this — it'd be more correct to close the issue as "not planned". Because this issue is not about text search in bot.

**Comment by 9dogs** [comment]
If this issue is still relevant - feel free to reopen it.

**Comment by AlexWayfer** [comment]
> If this issue is still relevant - feel free to reopen it.

I literally can't. :sweat_smile: 

![image](https://user-images.githubusercontent.com/6510020/223112865-50b69c57-b027-4811-987c-a2109f3f0cf9.png)

I suggest to wait more feedback. Maybe from myself in the feature, who knows.
