### ISSUE TITLE
Album/artist

### ISSUE THREAD

**Issue by deadevill** [9dogs/tg-odesli-bot#34]
Brother please add artist/ album features

**Comment by AlexWayfer** [comment]
> Brother please add artist/ album features

What do you mean? Create an artist and release an album? :sweat_smile: 

Or search by artist/album? Odesli supports search by album URL, and the bot too:

![image](https://user-images.githubusercontent.com/6510020/158331752-cf7ece3a-3612-4bc9-92b1-a5056f8714c0.png)

But it doesn't support search by Artist URL:

![image](https://user-images.githubusercontent.com/6510020/158331857-faf4ccaa-4324-4f8a-8ffc-2d2d26395326.png)

So, you should write a feature request to Odesli.co, and in case of implementation it probably will work with bot automatically.

And I think we can close this issue.

**Comment by deadevill** [comment]
Thanks for the bot and Bro please add Qobuz Streaming Service

**Comment by AlexWayfer** [comment]
> Thanks for the bot and Bro please add Qobuz Streaming Service

It should be a separate issue. And, not for the bot, because again: do you see Qobuz links on Odesli.co? I don't. So, please, write to them.
