### ISSUE TITLE
Apple music link incorrect format

### ISSUE THREAD

**Issue by vdmklchv** [9dogs/tg-odesli-bot#39]
Please fix Apple music link format.
Sample from odesli bot is this - https://geo.music.apple.com/us/album/_/1549781001?mt=1&app=music&ls=1&at=1000lHKX&ct=api_http&itscg=30200&itsct=odsl_m

![image](https://user-images.githubusercontent.com/63234544/213200606-3a9fee56-093a-489e-9095-1549c4157102.png)

it adds geo prefix to URL, while the installed app on the phone does not recognize it and it is opened in browser.

If we remove geo and use URL  - https://music.apple.com/us/album/_/1549781001?mt=1&app=music&ls=1&at=1000lHKX&ct=api_http&itscg=30200&itsct=odsl_m  it opens correctly in the app.

**Comment by 9dogs** [comment]
I believe we take these links from the Odesli service without any changes, but I'll look into it. So simply removing `geo.` is enough?

**Comment by vdmklchv** [comment]
Yes, we can confirm that on Android devices Apple music app can correctly be open without geo. prefix. We, however, are unable to see if it changes something on Apple devices, but I believe it should work ok there both ways, with and without geo and only Android app has problems opening it.

**Comment by AlexWayfer** [comment]
I'd like to see this in production. There are still links with `geo`.

**Comment by 9dogs** [comment]
My bad. I dropped Python 3.7 support and the package hadn't been updated automatically on the server. Could you check again? Should be working now.

**Comment by AlexWayfer** [comment]
I see no `geo` now. Thank you.
