### ISSUE TITLE
New spotify link type

### ISSUE THREAD

**Issue by fr33mang** [9dogs/tg-odesli-bot#44]
Found out that bot doesn't work with link

![image](https://user-images.githubusercontent.com/13254668/230776940-4f4e48a1-1522-4934-bab3-337303021fb5.png)

Firsly, I tried to check if [song.link](https://song.link/) works with that url type, but it didn't. So I emailed support about the problem and a couple of days ago they've fixed it. 

![image](https://user-images.githubusercontent.com/13254668/230778367-ced0884f-d79c-440b-a798-d5e4749a244e.png)

So now I'm going to fix Spotify regexp, since now it shows something strange for that link

![image](https://user-images.githubusercontent.com/13254668/230778308-49a08758-568c-4592-b01b-9775885d7f29.png)

**Comment by 9dogs** [comment]
Hey man, thanks for going the extra mile! Should work now.

**Comment by fr33mang** [comment]
Happy to contribute into such a great bot. I use it just everyday
