### ISSUE TITLE
Inline mode

### ISSUE THREAD

**Issue by AlexWayfer** [9dogs/tg-odesli-bot#5]
Hello! Telegram bots can be inline: https://core.telegram.org/bots/inline

**Comment by 9dogs** [comment]
Hi!
Unfortunately, odesli.co service does not provide "search for song" functionality, it can only search by URL. Thus, inline request should contain URL as well, which is quite off of my usual usage pattern when URL is shared from music app like Deezer or Google Music.
Could you please describe the use case you have in mind with inline usage?

**Comment by AlexWayfer** [comment]
> Unfortunately, odesli.co service does not provide "search for song" functionality

It does:

**Comment by 9dogs** [comment]
> Maybe API does not… but you can look into DevTools and see requests. 😉
Yes, I forgot to mention "through API"🙂. It seems odesli is using iTunes search to get the URL first. I will read iTunes' ToS and see whether it can be done.

> I thought about @odesli URL, but yes, it can be less comfortable in most cases. But… why not?
I'll test it. I cannot work out from Telegram docs if inline and PM modes are mutually exclusive for bots.

**Comment by AlexWayfer** [comment]
**side note: insert an empty line after quote to finish it**

> I will read iTunes' ToS and see whether it can be done.

Thank you!

> I'll test it. I cannot work out from Telegram docs if inline and PM modes are mutually exclusive for bots.

I understand, but as I know, they're not exclusive.

**Comment by 9dogs** [comment]
Inline mode is added, type `@odesli_bot` to summon (I guess short names like `@gif` are only for official bots). 
As for song searches - iTunes API has a rate limit of 20 requests per minute, so it's not an option. I'll check other services APIs later.

**Comment by AlexWayfer** [comment]
Thank you! Seems working.

**Comment by Satont** [comment]
@9dogs thank you for inline mode. Very useful feauture.

**Comment by 9dogs** [comment]
@Satont you are more than welcome! Thanks to @AlexWayfer for suggestion.
