### ISSUE TITLE
add shazam and etc support

### ISSUE THREAD

**Issue by jimdi** [9dogs/tg-odesli-bot#51]
https://www.shazam.com/track/692959900/forgether?referrer=share
for example

**Comment by AlexWayfer** [comment]
https://odesli.co/https://www.shazam.com/track/692959900/forgether?referrer=share

Redirects to 404.

How is that possible?

**Comment by jimdi** [comment]
> How is that possible?

at now shazam is not supported, as I know

**Comment by AlexWayfer** [comment]
So, we can't support Shazam in the Odesli bot if Odesli doesn't support it by itself.

**Comment by jimdi** [comment]
whoops. little misunderstanding. thx

**Comment by AlexWayfer** [comment]
No problem. You can contact Odesli, if you want such feature. Bot probably will support it automatically.
