### ISSUE TITLE
Make bot available inline in chats

### ISSUE THREAD

**Issue by 0x49D1** [9dogs/tg-odesli-bot#8]
Just why not? It's natural to just ask bot right in the chat and select the result -> send it into the chat.. 
https://core.telegram.org/bots/inline

**Comment by 9dogs** [comment]
Inline mode should work (see https://github.com/9dogs/tg-odesli-bot/issues/5). Are you experiencing any troubles with it?

**Comment by 0x49D1** [comment]
Ops! My bad, I was trying @odesli, not @odesli_bot!
Thanks!
